name: 'Get Deployment Environments from PR'
description: 'Extract environment names from a PR Ref into a string list output'
inputs:
  token:
    required: true
    description: The token provided by GitHub actions via secrets.GITHUB_TOKEN
  repository:
    required: true
    description: Target Repository URL slug (<orgname>/<reponame>)
  ref:
    required: true
    description: PR Ref to check for deployment environments
  delete_environments:
    required: true
    description: Whether or not to delete environments for any deployments discovered
outputs:
  environmentNameList:
    description: List of environment names in string format
  deploymentsFound:
    description: bool value to indicate whether or not deployments were found for the ref
runs:
  using: 'node12'
  main: 'dist/index.js'