# This is a basic workflow to help you get started with Actions

name: Copy from CSV to Issues to Boards

# Controls when the action will run. Triggers the workflow on manual triggers
on: 
  workflow_dispatch:
    inputs:
      TargetRepoSlug:
        description: 'Target Repository URL slug (<orgname>/<reponame>)'     
        required: true
      CreateProject:
        description: 'Whether you want a project board to be created or not. ("true" or "false")'     
        required: true
      ProjectName:
        description: 'Name of the project board to be created'     
        required: true
      CsvFilePath:
        description: 'Name of CSV file in the root of this repo and branch to create issues from'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Issue-Creation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Create CSV Issues
      uses: ./
      id: Create_Issue_CSV
      with:
        GITHUB_TOKEN: ${{ secrets.SVC_DEVOPS_BOT_TOKEN }}
        TargetRepoSlug: ${{ github.event.inputs.TargetRepoSlug }}
        CreateProject: ${{ github.event.inputs.CreateProject }}
        ProjectName: ${{ github.event.inputs.ProjectName }}
        CSVFilePath: ${{ github.event.inputs.CsvFilePath }}


